spring:
  cloud:
    stream:
      bindings:
        projectInitialization:
          destination: project-initialization
        initProjectWarehouse-in-0:
          destination: project-initialization
          group: warehouse
        initSystemConfig-in-0:
          destination: project-initialization
          group: systemConfig
        approveProject:
          destination: approve-project
        approveProject-in-0:
          destination: approve-project
          group: project
        warehouseInitialize:
          destination: warehouse-initialize
        initWarehouseSkeleton-in-0:
          destination: warehouse-initialize
          group: warehouse
        initWarehouseMember-in-0:
          destination: warehouse-initialize
          group: member
        versionPublish:
          destination: version-publish
        versionPublishStrategy-in-0:
          destination: version-publish
          group: version
        versionPublishApprove:
          destination: version-publish-approve
        versionPublishApprove-in-0:
          destination: version-publish-approve
          group: version
      function:
        definition: initProjectWarehouse;initSystemConfig;initWarehouseSkeleton;initWarehouseMember;versionPublishStrategy;versionPublishApprove;approveProject